"""
src/reporter.py — Generate a Markdown run report and matplotlib charts.

Outputs:
  - output/report_<timestamp>.md   : Human-readable run summary
  - output/charts/scatter_<ts>.png : Lat/lon scatter plot coloured by magnitude
  - output/charts/bars_<ts>.png    : Bar chart of events per region
"""

from __future__ import annotations

import os
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from src.logger_config import get_logger
from src.models import SeismicEvent

logger = get_logger("reporter")


def generate_report(
    events: List[SeismicEvent],
    quality_entries: List[Dict[str, Any]],
    quarantine_records: List[Any],
    run_metadata: Dict[str, Any],
    cfg: Dict[str, Any],
) -> Optional[str]:
    """
    Generate a Markdown report for this pipeline run.

    Returns the path to the generated report file, or None on failure.
    """
    report_dir = Path(cfg.get("output", {}).get("report_dir", "output"))
    report_dir.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    report_path = report_dir / f"report_{timestamp}.md"

    high_risk_threshold = cfg.get("risk_score", {}).get("high_risk_threshold", 70)
    high_risk_events = [e for e in events if e.risk_score > high_risk_threshold]
    tsunami_events = [e for e in events if e.has_tsunami]

    # ── Aggregate by region ───────────────────────────────────────────────────
    region_counts: Dict[str, int] = {}
    region_max_mag: Dict[str, float] = {}
    for ev in events:
        region_counts[ev.region_id] = region_counts.get(ev.region_id, 0) + 1
        region_max_mag[ev.region_id] = max(region_max_mag.get(ev.region_id, 0.0), ev.magnitude)

    max_mag_event: Optional[SeismicEvent] = max(events, key=lambda e: e.magnitude) if events else None

    # ── Build Markdown content ────────────────────────────────────────────────
    lines: List[str] = []
    lines.append(f"# 🌍 Atlas Reinsurance Analytics — Seismic Pipeline Report")
    lines.append(f"\n**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}")
    lines.append(f"**Mode:** `{run_metadata.get('mode', 'unknown')}`")
    if run_metadata.get("start_date"):
        lines.append(f"**Date range:** `{run_metadata['start_date']}` → `{run_metadata['end_date']}`")
    lines.append("")

    # Summary section
    lines.append("---")
    lines.append("\n## 📊 Global Summary\n")
    lines.append(f"| Metric | Value |")
    lines.append(f"|---|---|")
    lines.append(f"| Total events loaded | **{len(events)}** |")
    lines.append(f"| Events discarded (quality) | {len(quality_entries)} |")
    lines.append(f"| Events quarantined | {len(quarantine_records)} |")
    lines.append(f"| Tsunami alerts | 🌊 **{len(tsunami_events)}** |")
    lines.append(f"| High risk events (score > {high_risk_threshold}) | ⚠️ **{len(high_risk_events)}** |")

    if max_mag_event:
        lines.append(
            f"| Maximum magnitude | **{max_mag_event.magnitude:.1f}** "
            f"({max_mag_event.place}) |"
        )

    # High risk events table
    if high_risk_events:
        lines.append("\n---")
        lines.append(f"\n## ⚠️ High Risk Events (risk_score > {high_risk_threshold})\n")
        lines.append("| Event ID | Magnitude | Place | Depth (km) | Risk Score | Region | Alert |")
        lines.append("|---|---|---|---|---|---|---|")
        for ev in sorted(high_risk_events, key=lambda e: e.risk_score, reverse=True)[:50]:
            alert_str = ev.alert_level or "—"
            lines.append(
                f"| `{ev.event_id}` | {ev.magnitude:.1f} | {ev.place[:40]} | "
                f"{ev.depth_km:.1f} | **{ev.risk_score:.1f}** | {ev.region_id} | {alert_str} |"
            )

    # Tsunami alerts
    if tsunami_events:
        lines.append("\n---")
        lines.append("\n## 🌊 Tsunami Alerts\n")
        lines.append("| Event ID | Magnitude | Place | Region | Event Time |")
        lines.append("|---|---|---|---|---|")
        for ev in tsunami_events:
            lines.append(
                f"| `{ev.event_id}` | {ev.magnitude:.1f} | {ev.place[:40]} | "
                f"{ev.region_id} | {ev.event_time.strftime('%Y-%m-%d %H:%M UTC')} |"
            )

    # Region breakdown
    lines.append("\n---")
    lines.append("\n## 🗺️ Events by Region\n")
    lines.append("| Region | Events | Max Magnitude |")
    lines.append("|---|---|---|")
    for rid, cnt in sorted(region_counts.items(), key=lambda x: x[1], reverse=True):
        lines.append(f"| {rid} | {cnt} | {region_max_mag.get(rid, 0.0):.1f} |")

    lines.append("\n---")
    lines.append(
        f"\n*Report generated by Atlas RA Seismic ETL Pipeline · "
        f"Run ID: {run_metadata.get('run_id', 'N/A')}*\n"
    )

    report_path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("Report written to %s", report_path)

    # ── Generate charts ───────────────────────────────────────────────────────
    _generate_charts(events, region_counts, cfg, timestamp)

    return str(report_path)


def _generate_charts(
    events: List[SeismicEvent],
    region_counts: Dict[str, int],
    cfg: Dict[str, Any],
    timestamp: str,
) -> None:
    """Generate scatter plot and bar chart if matplotlib is available."""
    try:
        import matplotlib
        matplotlib.use("Agg")  # non-interactive backend
        import matplotlib.pyplot as plt
        import numpy as np
    except ImportError:
        logger.warning("matplotlib not installed — skipping chart generation.")
        return

    charts_dir = Path(cfg.get("output", {}).get("charts_dir", "output/charts"))
    charts_dir.mkdir(parents=True, exist_ok=True)

    if not events:
        logger.info("No events to chart.")
        return

    lons = [e.longitude for e in events]
    lats = [e.latitude for e in events]
    mags = [e.magnitude for e in events]

    # ── Scatter plot: lat/lon coloured by magnitude ───────────────────────────
    fig, ax = plt.subplots(figsize=(14, 8), facecolor="#1a1a2e")
    ax.set_facecolor("#16213e")

    scatter = ax.scatter(
        lons, lats,
        c=mags,
        cmap="YlOrRd",
        s=[max(2, (m ** 3) * 0.8) for m in mags],
        alpha=0.75,
        linewidths=0.3,
        edgecolors="white",
    )
    cbar = fig.colorbar(scatter, ax=ax, pad=0.01)
    cbar.set_label("Magnitude", color="white", fontsize=11)
    cbar.ax.yaxis.set_tick_params(color="white")
    plt.setp(cbar.ax.yaxis.get_ticklabels(), color="white")

    ax.set_xlabel("Longitude", color="white", fontsize=12)
    ax.set_ylabel("Latitude", color="white", fontsize=12)
    ax.set_title(
        "Global Seismic Events — Atlas RA Pipeline",
        color="white", fontsize=14, fontweight="bold",
    )
    ax.tick_params(colors="white")
    for spine in ax.spines.values():
        spine.set_edgecolor("#444")

    ax.grid(True, alpha=0.2, color="gray")
    plt.tight_layout()

    scatter_path = charts_dir / f"scatter_{timestamp}.png"
    fig.savefig(scatter_path, dpi=150, bbox_inches="tight", facecolor=fig.get_facecolor())
    plt.close(fig)
    logger.info("Scatter chart saved: %s", scatter_path)

    # ── Bar chart: events per region ──────────────────────────────────────────
    if region_counts:
        regions_sorted = sorted(region_counts.items(), key=lambda x: x[1], reverse=True)
        labels = [r[0] for r in regions_sorted]
        counts = [r[1] for r in regions_sorted]

        palette = plt.colormaps["plasma"].resampled(len(labels))
        colors = [palette(i) for i in range(len(labels))]

        fig2, ax2 = plt.subplots(figsize=(12, 6), facecolor="#1a1a2e")
        ax2.set_facecolor("#16213e")
        bars = ax2.bar(labels, counts, color=colors, edgecolor="white", linewidth=0.5)

        for bar, cnt in zip(bars, counts):
            ax2.text(
                bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 0.3,
                str(cnt),
                ha="center", va="bottom", color="white", fontsize=9,
            )

        ax2.set_xlabel("Region", color="white", fontsize=12)
        ax2.set_ylabel("Number of Events", color="white", fontsize=12)
        ax2.set_title(
            "Seismic Events by Monitoring Region",
            color="white", fontsize=14, fontweight="bold",
        )
        ax2.tick_params(colors="white", axis="both")
        plt.xticks(rotation=30, ha="right", color="white")
        for spine in ax2.spines.values():
            spine.set_edgecolor("#444")
        ax2.grid(axis="y", alpha=0.2, color="gray")

        plt.tight_layout()
        bars_path = charts_dir / f"bars_{timestamp}.png"
        fig2.savefig(bars_path, dpi=150, bbox_inches="tight", facecolor=fig2.get_facecolor())
        plt.close(fig2)
        logger.info("Bar chart saved: %s", bars_path)
